### ISSUE TITLE
[BUG] M300 beep macro uses invalid value when using non-pwm beeper

### ISSUE THREAD

**Issue by pwNBait** [jschuh/klipper-macros#119]
Before making a report please ensure you've followed the troubleshooting steps at:
https://github.com/jschuh/klipper-macros#troubleshooting

You can also get general troubleshooting assistance in the Q&A Discussion tab:
https://github.com/jschuh/klipper-macros/discussions/categories/q-a

**Describe the bug**
![image](https://github.com/jschuh/klipper-macros/assets/11964147/338d508a-b4f8-4aca-8ef0-6d5e22890634)
The M300 macro uses an invalid value when using a non-pwm beeper. 
Since a non-pwm beeper cannot have a scale setting, the macro uses a default value of 1.0.
` settings["output_pin beeper"].scale|default(1.0) * 0.5`
However, the default 1.0 * 0.5 results in an invalid value for the digital SET_PIN command.
It should be 1.0 or 0.0. 

**Klipper config**
I am using an Ender 3 v2 Neo

[output_pin beeper]
pin: PB13

**Comment by pwNBait** [comment]
That makes sense. Thanks for taking a look.

**Comment by pwNBait** [comment]
Sure. My printer is busy at the moment. I'll be able to test the change tommorrow.
I'll let you know if the change works.

**Comment by pwNBait** [comment]
I tested the change and it works perfectly.
Let me know if there is anything else to test.

**Comment by jschuh** [comment]
Thanks, that's all I needed. I'll land it on main soon.
