### ISSUE TITLE
How to make the bed move forward after printing, and not backward?

### ISSUE THREAD

**Issue by Serj121** [jschuh/klipper-macros#135]
How to make the bed move forward after printing, and not backward?
I tried to do it in gcode_macro _km_options, but it doesn't work.
[config.zip](https://github.com/jschuh/klipper-macros/files/11780458/config.zip)

**Comment by jschuh** [comment]
This tracker is for reporting bugs. If you need help troubleshooting your config, please use the [Q&A section](https://github.com/jschuh/klipper-macros/discussions/categories/q-a).

That stated, the attached config is invalid. The [Klipper setup instructions](https://github.com/jschuh/klipper-macros#klipper-setup) provide a working config section you can customize. And the [start/end customization options](https://github.com/jschuh/klipper-macros#print_start) are described in full detail as well (take a look at `variable_start_end_park_y`).
