### ISSUE TITLE
Documentation for OrcaSlicer

### ISSUE THREAD

**Issue by buker** [jschuh/klipper-macros#162]
It will be good to have OrcaSlicer docs, how to configure it with your macros

`Failed to generate G-code for invalid custom G-code.
machine_start_gcode Parsing error at line 3: Not a variable name
PRINT_START_SET MODEL_MIN={bounding_box[0]},{bounding_box[1]} MODEL_MAX={bounding_box[3]},{bounding_box[4]}
                           ^
Please check the custom G-code or use the default custom G-code.`

**Comment by KaratsuFr** [comment]
i'm using Orca - you can follow the same way as you would configure for prusa
In Machine > Gcode follow the documentation
![image](https://github.com/jschuh/klipper-macros/assets/12607465/413fbd4e-7ac3-4444-add2-499b4fc95705)
