### ISSUE TITLE
Error "TOTAL_LAYER must have minimum of 0" after updating to latest layers.cfg

### ISSUE THREAD

**Issue by remigod86** [jschuh/klipper-macros#20]
I am getting the following errors after getting the latest version. Unfortunately, I am much too new in klipper to even understand how to correct/circumvent this issue. I have reverted to the previous version of layers.cfg in the meantime.

Extrude below minimum temp
6:22 PM
Extrude below minimum temp
See the 'min_extrude_temp' config option for details
6:22 PM
Error on 'SET_PRINT_STATS_INFO TOTAL_LAYER="-1"': TOTAL_LAYER must have minimum of 0

**Comment by jschuh** [comment]
Should be fixed now.
