### ISSUE TITLE
Z offset Issue

### ISSUE THREAD

**Issue by anilgunduzz** [jschuh/klipper-macros#21]
Hi,

I'm receiving "Error evaluating 'gcode_macro set_gcode_offset:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'bed_surfaces' " when I tried to click to the z offset buttons on dashboard.

![204156617-aaa85874-a2bd-4f2c-bc0f-8e06c478fd6b](https://user-images.githubusercontent.com/60423905/205217614-a6af15c4-33ff-40bf-9aea-a22bc4031354.png)

Could you please help?

Printer: Ender 3 v2
Mainboard: SKR Mini E3 V3

Best Regards.

**Comment by jschuh** [comment]
It sounds like you don't have a properly configured [`[save_variables]`](https://www.klipper3d.org/Config_Reference.html#save_variables) section. Make sure the `save_variables` section is present in your config and the path provided for `filename` is valid.
