### ISSUE TITLE
[BUG] - v0.8.8 issue with purge line not working anymore

### ISSUE THREAD

**Issue by KaratsuFr** [jschuh/klipper-macros#220]
**Describe the bug**
I was on 0.8.7 and update to 0.8.8 and since i got the bellow issue. i tried to change extruder to not relative since it was adressing that kind of issue else where and i tried to modify my model to make sure it was not related to disposal or else.
by reverting the draw.cfg to 0.8.7 it work again.

**Klipper errors**
```
!! {"code":"key112", "msg": "Move exceeds maximum extrusion (1.203mm^2 vs 0.640mm^2)
See the 'max_extrude_cross_section' config option for details", "values": [1.203, 0.640]}
```

**Comment by jschuh** [comment]
See the [discussion here](https://github.com/jschuh/klipper-macros/discussions/212#discussioncomment-7890302).
