### ISSUE TITLE
[Freature Request] Event for idling (_km_idle_timeout)

### ISSUE THREAD

**Issue by j16sdiz** [jschuh/klipper-macros#227]
Expose the Timeout Idle for event.

Reasonale: I have NEOPIXEL LEDs, would be great if they can dim after idle.

**Comment by gretel** [comment]
think that is possible rn? https://github.com/jschuh/klipper-macros/blob/14840a4f1cdc38358d3c2097088e58ac5d502914/README.md?plain=1#L220
