### ISSUE TITLE
[BUG] Too Much Retract on PRINT_END for Microswiss Hotends

### ISSUE THREAD

**Issue by SSPW** [jschuh/klipper-macros#229]
I am getting too much anti ooze rectract at the end of prints and clogging.
Looks like there are 3 lines with retraction for a total of 7mm (1 + 1 + 5) mm, which is way too much for a microswiss hotends.
I cant edit the macro...

Could this be made a parameter? If not, how do i unlock and edit the macro and make it stick?

![bug](https://github.com/jschuh/klipper-macros/assets/17904893/fc39ea5d-62b4-47c0-b7a5-a56d3e61710a)

**Comment by gretel** [comment]
making the retraction settings configurable in a generic way be cool. thank you

**Comment by Heratiki** [comment]
Are you using a MicroSwiss Direct Drive setup as well as the MicroSwiss hotend?

**Comment by jschuh** [comment]
I had this derived from `load_priming_length` locally, and just pushed that to dev in 5292fbf. That stated, feature requests belong in the [discussion section](https://github.com/jschuh/klipper-macros/discussions/categories/ideas).
