### ISSUE TITLE
[BUG] Option 'relative_reference_index' is not valid in section 'bed_mesh'

### ISSUE THREAD

**Issue by M3HNGRY** [jschuh/klipper-macros#231]
Updated Klipper to v0.12.0-111-g4f00f219 running klipper-macros v0.8.8-0-g14840a4f. 

![image](https://github.com/jschuh/klipper-macros/assets/131578650/5a677fbc-aae2-4072-91f4-480402aaae82)

**Comment by Gamithon** [comment]
To fix this after updating klipper:
Remove the depreciated "relative_reference_index" from you [bed_mesh] gcode (inside printer.cfg)
I also had to remove the "relative_reference_index: #" line as well
It is recommended to use "zero_reference_position" 

I didn't see any functionality differences after making the above changes. Is there any major differences between the two commands?

**Comment by gretel** [comment]
is this project maintained?

**Comment by jschuh** [comment]
As noted above, this is unrelated to the macros; you're getting it because Klipper removed `relative_reference_index`.
