### ISSUE TITLE
BigTreeTech - Pi v1.2 Macros [BUG]

### ISSUE THREAD

**Issue by Skybound420** [jschuh/klipper-macros#232]
Before making a report please ensure you've followed the troubleshooting steps at:
https://github.com/jschuh/klipper-macros#troubleshooting

Just a brief memo that can be taken as rhetorical.  I'm new to Klipper and new to macros, however I did make a backup of my config and am proceeding at my own risk.  The (BUG?) I've encountered is regarding the Troubleshooting itself in that the following 2 commands are not recognized by my Klipper.

CHECK_KM_CONFIG 
_INIT_SURFACES 

Perhaps this is due to my version of Pi that uses the CB1 operating system.  I just assumed all things Klipper would be Kosher, but perhaps I am wrong.  Wish me luck, and thank you for your repository, I hope it works out for me.

**Comment by jschuh** [comment]
Troubleshooting questions go in [discussions](https://github.com/jschuh/klipper-macros/discussions/categories/q-a).
