### ISSUE TITLE
I get an error Existing command 'SET_PRINT_STATS_INFO' not found in gcode_macro rename

### ISSUE THREAD

**Issue by SplinMS** [jschuh/klipper-macros#247]
I have an Ender 6 so I'm using the firmware [Desuuuu] (https://github.com/Desuuuu/klipper)
Installed according to instructions [](https://3dprintbeginner.com/how-to-install-klipper-on-creality-ender-6/) and didn't change anything
I get an error Existing command 'SET_PRINT_STATS_INFO' not found in gcode_macro rename immediately after installation.
Everything is updated to the latest versions. Perhaps the problem is that I cannot update the Klipper itself more than in that repository. But I would like to use these macros.

**Comment by jschuh** [comment]
Please check the discussion forum first for config troubleshooting, and leave questions there if you can't find an answer. [This specific question has already been answered.](https://github.com/jschuh/klipper-macros/discussions/188#discussioncomment-7535744)
