### ISSUE TITLE
Layers.cfg file calls a macro that doesn't exist

### ISSUE THREAD

**Issue by derekyle** [jschuh/klipper-macros#29]
A macro in Layers.cfg calls SET_PRINT_STATS_INFO which throws an error on my system. Should this macro be included somewhere? It looks like it is not a command that Klipper recognizes at this time.

**Comment by jschuh** [comment]
SET_PRINT_STATS_INFO is a Klipper gcode command [introduced last October](https://github.com/Klipper3d/klipper/commit/b0ffb269d2ac8dc19ae6879d80718b8c60ab60de). It seems like your Klipper install is older, but updating should resolve this.

**Comment by derekyle** [comment]
Yes, that was it. I was using the newest version of the OctoKlipperPi image, not realizing that it currently ships with a little bit older version of Klipper.
