### ISSUE TITLE
Macro for loading and unloading of filament is not working

### ISSUE THREAD

**Issue by flow23** [jschuh/klipper-macros#31]
2:41 PM - Error evaluating 'gcode_macro _load_unload:gcode': TypeError: '<' not supported between instances of 'str' and 'int'
2:41 PM - load_filament LENGTH=150 SPEED=1500 EXTRUDER=extruder MINIMUM=250

I guess there is a problem with type conversion.

**Comment by jschuh** [comment]
Interesting... I don't think the `SPEED` parameter had worked properly since I first checked it in. I guess that means you're the first person to actually use it. Anyway, it should be fixed now.

**Comment by flow23** [comment]
Will try it next week. Thanks.

**Comment by justlikeef** [comment]
Even though I got the error, it worked for me from the Mainsail web page, but never worked from the touchscreen interface on my Pi through KlipperScreen
