### ISSUE TITLE
Custom Start_Print

### ISSUE THREAD

**Issue by sogeniusio** [jschuh/klipper-macros#36]
Trying to adopt this new setup and I'm unsure how to incorporate my normal start print macro. I run a Z_TILT_ADJUST and CALIBRATE_Z job before each print. I don't see where it'd make sense to drop this in. I'm also using a Euclid Probe, so I need to include M401 to pick up the probe and M402 to stow it.

```sh
[gcode_macro G32]
gcode: 
	G28
	QUERY_PROBE
	M401
	Z_TILT_ADJUST
	CALIBRATE_Z

[gcode_macro PRINT_START]
gcode: 

	{% set BED_TEMP = params.BED|default(60)|float %}
	{% set EXTRUDER_TEMP = params.EXTRUDER|default(245)|float %}
	{% set CHAMBER_TEMP = params.CHAMBER|default(21)|float %}
        {% set PREHEAT = (EXTRUDER_TEMP * 0.6)|default(120)|float %}
  	M104 S{PREHEAT} 
	M190 S{BED_TEMP}    
  	G32 
        G90         
	M220 S100     
	M221 S100  
  	M190 S{BED_TEMP}  
        M109 S{EXTRUDER_TEMP}  
        G92 E0      
	QUERY_PROBE
	M402
```

**Comment by jschuh** [comment]
I don't use dockable probes or quad gantry leveling on any of my machines, but I've been told that other people using these macros do. So, I'd think you just want to override `BED_MESH_CALIBRATE` with something like this to undock the probe, level the gantry, generate the mesh, and then dock the probe:

```
[gcode_macro BED_MESH_CALIBRATE]
rename_existing:    BED_MESH_CALIBRATE_BASE
gcode:
  M401
  Z_TILT_ADJUST
  CALIBRATE_Z
  BED_MESH_CALIBRATE_BASE {rawparams}
  M402
```

That will get called in START_PRINT after the bed reaches temperature and stabilizes, but immediately before the print begins.
