### ISSUE TITLE
[BUG] Is there a way to cancel PRINT_START?

### ISSUE THREAD

**Issue by ericderace** [jschuh/klipper-macros#40]
**Describe the bug**
I find myself having to use the emergency stop (M112?) to stop the PRINT_START macro. On my printer, it takes a while to warm up and complete the bed mesh (10-20 minutes), meanwhile I find a reason to stop it but the only way I can is to use the E-Stop. I then have to restart the firmware.

Hitting cancel print does not work until the macro finished.

Is there another way to stop the PRINT_START Macro?

**Comment by jschuh** [comment]
Unfortunately no, that's just not how Klipper works. All the commands are queued and execute in order. The only special case is for `M112`, where Klipper executes a shutdown immediately on issuance regardless of the queue or current printer state.
