### ISSUE TITLE
[IMPROVEMENT] In beep.cfg add check for zero

### ISSUE THREAD

**Issue by MJeka** [jschuh/klipper-macros#45]
CYCLE_TIME={ 1.0/S if S > 0 else 1 }

**Comment by jschuh** [comment]
The `m300` macro already ensures that the integer value of `S` is at least `1`: https://github.com/jschuh/klipper-macros/blob/bb6796c502654678a7f5fc87c56ebf62bff25ee3/beep.cfg#L12

In the future please validate any suspected issue before filing, to verify that a bug is present.
