### ISSUE TITLE
Error when running bed_mesh_calibrate_fast

### ISSUE THREAD

**Issue by midhunmonachan** [jschuh/klipper-macros#49]
`Error evaluating 'gcode_macro bed_mesh_calibrate_fast:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'gcode_macro bed_mesh_calibrate'`

**Comment by midhunmonachan** [comment]
Update:
I added [include klipper-macros/optional/bed_mesh.cfg] to my config and it doesn't give that error. It was happening during start_print command. Is it how it's supposed to be?

Thanks

**Comment by jschuh** [comment]
Closing report as it does not follow the [troubleshooting and bug reporting guidance](https://github.com/jschuh/klipper-macros#troubleshooting).
