### ISSUE TITLE
Readme correction

### ISSUE THREAD

**Issue by appleimperio** [jschuh/klipper-macros#5]
First of all thank you these Macros are amazing I don't understand the magic behind them but they work for example when is probing the bed it only probe where is going to print? that's genius. I have to play with changing the surfaces because I have been looking for that for a long time. 

There is a warning in the Read me that you need to have bed_heater configured I think you mean heater_bed.

**Comment by jschuh** [comment]
Ah, thanks for the catch, and glad to see someone else finds these macros useful. 13e3e1b176ac49f1c8408830852f3cb9f94c3b32 should fix that and a few other doc issues as well.
