### ISSUE TITLE
Move out of range

### ISSUE THREAD

**Issue by cmcfalls2** [jschuh/klipper-macros#54]
I am getting a move out of range error every time I start a print. It is attempting to move it to X 245 and my max is set to X 235. Where can I resolve this? I have looked all over and tried to get help elsewhere (discord server) but no one is able to decipher the macros. I believe it has something to do with the draw purge line process, because it happens immediately after the print area mesh probe.

**Comment by jschuh** [comment]
Closing report as it does not follow the [troubleshooting and bug reporting guidance](https://github.com/jschuh/klipper-macros#troubleshooting).
