### ISSUE TITLE
Mistake in providet "add to moonraker.conf"

### ISSUE THREAD

**Issue by DragonPerl** [jschuh/klipper-macros#57]
I copied the code as in the box and pasted it to my moonraker.conf. 
The Button showed me an error.

To solve the problem i simply switched the lines "path: ..." and "origin: ...", as the rest of the configs where written like this.

'''
[update_manager klipper-macros]
type: git_repo
path: ~/printer_data/config/klipper-macros # UPDATE THIS FOR YOUR PATH!!!
origin: https://github.com/jschuh/klipper-macros.git
primary_branch: main
is_system_service: False
managed_services: klipper
'''

Now everything's ok.

Thanks for your awesome work, try to figure out all of the functionality!
Greetings from Austria!
Markus

**Comment by jschuh** [comment]
Glad you were able to get your issue sorted, but I can't imagine that is had anything to do with the order of these fields. All my machines actually have configs identical to the readme, and I've seen many other installs successfully using it.

More importantly, if you look at Moonraker's [`confighelper`](https://github.com/Arksine/moonraker/blob/80920dd8723b7dac6d176500fed88d81149f22b2/moonraker/confighelper.py) you'll see that it parses the full config set using python's [`configparser`](https://docs.python.org/3/library/configparser.html) library and performs variable expansion of Jinja2 templates before handing off a synthesized `dict` of the config to any modules. So, as the code is currently written it's literally impossible for any submodules (including [`UpdateManager`](https://github.com/Arksine/moonraker/blob/fd5ea0c6a45fb04baf21014d1505f3d4ade791db/moonraker/components/update_manager/update_manager.py#L67)) to even know the order of config fields in the file, much less have a dependency on them.
