### ISSUE TITLE
Load existing bed mesh instead of probing

### ISSUE THREAD

**Issue by raechten** [jschuh/klipper-macros#58]
Apart from overriding PRINT_START, is there a way to load an existing bed mesh instead of probing the bed before each print? Especially with shorter prints, this greatly reduces the overall time

**Comment by jschuh** [comment]
Overriding `PRINT_START` is quite easy; [the docs have a template you can copy](https://github.com/jschuh/klipper-macros#print-start-and-end). You could also duplicate the old Klipper behavior by loading the profile in the `gcode` for your `_km_options`, which runs at Klipper startup. Or you could just load it in `_km_options` `variable_start_gcode_before_print` before each print.

**Comment by jschuh** [comment]
There's a [suggestion in the Ideas discussion](https://github.com/jschuh/klipper-macros/discussions/96) of tying this to the bed sheet selection, which I'm thinking about doing.
