### ISSUE TITLE
[BUG] Existing command 'SET_PRINT_STATS_INFO' not found in gcode_macro

### ISSUE THREAD

**Issue by RedemptionOne** [jschuh/klipper-macros#73]
just installed and restarted klipper the following error comes out Existing command 'SET_PRINT_STATS_INFO' not found in gcode_macro'

Using fluidd on creality sonic pad

**Comment by jschuh** [comment]
The Sonic Pad is running an old version of Klipper; there's a bit more context on the problem in issue #62.

I should add that Mainsail and Fluidd are increasingly adding integrations that depend on `SET_PRINT_STATS_INFO` (e.g. 330422ffc852b93cb1689a76eb8c43caa00d4046), so the situation is only going to get worse if Creality doesn't update their fork to a more recent version of Klipper.
