### ISSUE TITLE
[BUG] no heater bed

### ISSUE THREAD

**Issue by cygauvan** [jschuh/klipper-macros#74]
Before making a report please ensure you've followed the troubleshooting steps at:
https://github.com/jschuh/klipper-macros#troubleshooting

**Describe the bug**
Please provide a clear and concise description of the issue.

**Klipper errors**
Paste the full text of any commands that trigger the error, along with any Klipper error messages and relevant portions of the Klipper logs.

**Klipper config**
Paste any relevant sections from your Klipper config, or attach the full config if you prefer. Please also note any other macros you are including as part of your config. **Bug reports without attached configs will most likely be closed.**

bonjour je possede une dagoma DU V2 TMC et je n'ai pas de plateau chauffant mais les differents macros me demandent de creer une section heater bed avec un sensor type, comment puis je modifier 
merci

**Comment by jschuh** [comment]
As [stated in the readme](https://github.com/jschuh/klipper-macros#a-few-warnings) a heater bed is required.
