### ISSUE TITLE
[ENHANCEMENT] Better Params Control for Load/Unload filament 

### ISSUE THREAD

**Issue by fire1ce** [jschuh/klipper-macros#78]
Hey @jschuh thanks for your work!

I would like to ask if it's possible to add the ability to set the following (example provided at the bottom) parameters for the Load/Unload filament? The issue I have is that I can't set the desired parameters as default values right now, and when using KlipperScreen, it's a pain to enter the values via the "macros" menu, since it already has "load" and "unload" menus built-in which will execute the macro with the "minimum" calculated parameters.

Example for globals.cfg (part of them already exists)

```shelll
# Length (in mm) of filament to load (bowden tubes will be longer).
variable_load_length: 90.0
# Filament loading speed (in mm/m).
variable_load_speed: 300
# Length (in mm) of filament to unload.
variable_unload_length: 90.0
# Filament unloading speed (in mm/m).
variable_unload_speed: 300
# Length (in mm) of the filament loading that feeds at priming speed.
variable_load_priming_length: 25.0
# Default minimum temperature for LOAD_FILAMENT and UNLOAD_FILAMENT.
variable_load_unload_temperature: 220
```

**Comment by jschuh** [comment]
I'm not sure I understand the request. Are you asking for two additional parameters for unloading speed and length? If so, I guess I'm not clear on what value there is in having them different for unloading versus loading. Or maybe I'm missing something?

**Comment by fire1ce** [comment]
@jschuh about the differents for unloading/loading is not critical. the value that im realy missing is "variable load unload temperature" that i can predefined as a default. right now it usses the minimum temp + 5. 
is that posable to add?

**Comment by jschuh** [comment]
Let me think about it. It would be easy enough to add, but my concern is that it doesn't really make sense for multi-extruder setups and that the number of config parameters keeps growing unbounded.

**Comment by fire1ce** [comment]
> Let me think about it. It would be easy enough to add, but my concern is that it doesn't really make sense for multi-extruder setups and that the number of config parameters keeps growing unbounded.

Sure. By the way, you can maintain the same logic with the minimum temperature. For example, if the default temperature is set to 0 (below the minimum) in globals.cfg, it will execute the same logic as it does now. If the value in the overriding config is above the minimum temperature, then it will use that value.

**Comment by jschuh** [comment]
Yes, [that's how all the options that derive their defaults from config settings work](https://github.com/jschuh/klipper-macros/blob/46f8d6223a5abc1d942dc5491fb822f40c46edaf/globals.cfg#L134). The issue in this specific case is that it introduces a potential discontinuity between having a single global option versus behavior derived from per-extruder settings.

**Comment by jschuh** [comment]
I decided to land it as 8c13bd30a5aeb839ff1d76fcbccf087c682058bf along with some other changes today.

**Comment by fire1ce** [comment]
thanks. much appreciated!
