### ISSUE TITLE
Print Start loads filament but Print End doesn't unload it

### ISSUE THREAD

**Issue by mrhasbean** [jschuh/klipper-macros#98]
Hey @jschuh cool macros. I normally roll my own but saw a write up that mentioned yours so I thought I'd give them a run. 

I've got most things sussed I think, but just wondering if I have variable_load_length set and that amount of filament is loaded at the start, is it by design that it doesn't unload it at the end? 

It is just that if it doesn't unload it, which seems to be what is happening, then I start another print with the same filament, it will try to shove that amount of filament through the nozzle?

**Comment by jschuh** [comment]
'The `load_length` variable is used as a default value by the [filament macros](https://github.com/jschuh/klipper-macros#filament). It's not used in `PRINT_START` or `PRINT_END`.

In the future please use the [Q&A Discussion](https://github.com/jschuh/klipper-macros/discussions/categories/q-a) for config questions. I try to use the issue tracker solely for bug reports.
